//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicedenBilgiAlarakToplama.wsDortIslem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDortIslem.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/topla", ReplyAction="*")]
        int topla(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/carp", ReplyAction="*")]
        int carp(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fark", ReplyAction="*")]
        int fark(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bol", ReplyAction="*")]
        int bol(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ServicedenBilgiAlarakToplama.wsDortIslem.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ServicedenBilgiAlarakToplama.wsDortIslem.Service1Soap>, ServicedenBilgiAlarakToplama.wsDortIslem.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int topla(int a, int b) {
            return base.Channel.topla(a, b);
        }
        
        public int carp(int a, int b) {
            return base.Channel.carp(a, b);
        }
        
        public int fark(int a, int b) {
            return base.Channel.fark(a, b);
        }
        
        public int bol(int a, int b) {
            return base.Channel.bol(a, b);
        }
    }
}
